#! /usr/bin/env bash 

dollah_bill_yall=""

_git_money() {
	local bags_o_cash=( )
	bags_o_cash+=("https://www.youtube.com/watch?v=NnMuFqsmYSE#t=320")
	bags_o_cash+=("https://www.youtube.com/watch?v=Q8yLVXyTC58#t=44s")
	bags_o_cash+=("https://www.youtube.com/watch?v=e4oB6wYMcrI#t=5s")

	dollah_bill_yall=${bags_o_cash[$[$RANDOM % ${#bags_o_cash[@]}]]}
}

_git_money

if ! hash xdg-open 2> /dev/null; then
  open $dollah_bill_yall
else
  xdg-open $dollah_bill_yall &
fi
